name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ created ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Print xxx
        run: echo "${{ github.repository}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          #          images: chatfire/suno-free-api # ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository}}
          images: chatfire/image_name
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Asia/Shanghai'}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: chatfire/${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title'] }}:${{ steps.meta.outputs.tags }}

#          platforms: |
#            linux/386
#            linux/amd64
#            linux/arm/v5
#            linux/arm/v7
#            linux/arm64
#            linux/mips64le
#            linux/ppc64le
#            linux/s390x
#          build-args: |
#            APP_NAME=${{ env.APP_NAME }}
#            APP_VERSION=${{ env.APP_VERSION }}
#            tags: |
#            ${{ env.DOCKERHUB_REPO }}:latest
#            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}