name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  #  build:
  #
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Build the Docker image
  #        run: docker build . --file Dockerfile --tag suno-free-api:$(TZ=Asia/Shanghai date "+%Y_%m_%d__%H_%M_%S")

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chatfire/suno-free-api
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
#          tags: chatfire/suno-free-api:latest

#          platforms: |
#            linux/386
#            linux/amd64
#            linux/arm/v5
#            linux/arm/v7
#            linux/arm64
#            linux/mips64le
#            linux/ppc64le
#            linux/s390x
#          build-args: |
#            APP_NAME=${{ env.APP_NAME }}
#            APP_VERSION=${{ env.APP_VERSION }}
#            tags: |
#            ${{ env.DOCKERHUB_REPO }}:latest
#            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}